[package]
name = "signhash"
version = "0.0.1"
authors = ["Stephen Battista <stephen.battista@gmail.com>"]
edition = "2018"
 
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
# The name of a target is the name of the library that will be generated. This
# is defaulted to the name of the package, with any dashes replaced
# with underscores. (Rust `extern crate` declarations reference this name;
# therefore the value must be a valid Rust identifier to be usable.)
name = "signhash"
# This field points at where the crate is located, relative to the `Cargo.toml`.
path = "src/lib.rs"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 16
panic = 'unwind'
incremental = false
overflow-checks = true

[dependencies]
ring = "0.16.*"
data-encoding = "2.1.*"
scoped_threadpool = "0.1.*"
clap = "2.33.*"
serde = "1.0.*"
serde_yaml = "0.*"
rand = "0.7.*"
num_cpus = "1.10.*"
chrono = "0.4.*"
indicatif = "0.12.*"
walkdir = "2.2.*"
