[package]
name = "signhash"
version = "1.0.0"
authors = ["Stephen Battista <stephen.battista@gmail.com>"]
edition = "2018"



[features]
default = ["memmap"]


[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 16
panic = 'unwind'
incremental = false
overflow-checks = true

[dependencies]
ring = "0.16.16"
data-encoding = "2.3.*"
scoped_threadpool = "0.1.*"
clap = "2.33.*"
serde = "1.0.117"
serde_yaml = "0.8.14"
rand = "0.7.*"
num_cpus = "1.13.*"
chrono = "0.4.*"
indicatif = "0.15.*"
walkdir = "2.3.1"
log = "0.4.*"
blake3 = { version = "0.3.7", features = ["rayon"] }
memmap = { version = "0.7.0", optional = true }
anyhow = "1.0.34"