[package]
name = "signhash"
version = "0.0.1"
authors = ["Stephen Battista <stephen.battista@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
# The name of a target is the name of the library that will be generated. This
# is defaulted to the name of the package, with any dashes replaced
# with underscores. (Rust `extern crate` declarations reference this name;
# therefore the value must be a valid Rust identifier to be usable.)
name = "signhash"

# This field points at where the crate is located, relative to the `Cargo.toml`.
path = "src/lib.rs"

[dependencies]
ring = "0.16.7"
data-encoding = "2.1.2"
scoped_threadpool = "0.1.9"
clap = "2.33.0"
arrayref = "0.3.5"
serde = "1.0.99"
serde_yaml = "0.8"
rand = "0.7.0"
num_cpus = "1.10.1"
chrono = "0.4.9"
pretty-bytes = "0.2.2"
