[package]
name = "signhash"
version = "0.0.1"
authors = ["Stephen Battista <stephen.battista@gmail.com>"]
edition = "2018"



[features]
default = ["rayon", "c_avx512"]
c_avx512 = ["blake3/c_avx512"]
c_neon = ["blake3/c_neon"]
rayon = ["blake3/rayon", "memmap"]


[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 16
panic = 'unwind'
incremental = false
overflow-checks = true

[dependencies]
ring = "0.16.*"
data-encoding = "2.3.*"
scoped_threadpool = "0.1.*"
clap = "2.33.*"
serde = "1.0.*"
serde_yaml = "0.*"
rand = "0.7.*"
num_cpus = "1.13.*"
chrono = "0.4.*"
indicatif = "0.15.*"
walkdir = "2.2.*"
log = "0.4.*"
anyhow = "1.0.*"
blake3 = "0.1.*"
memmap = { version = "0.7.0", optional = true }

