[package]
name = "signhash"
version = "0.0.1"
authors = ["Stephen Battista <stephen.battista@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.7"
data-encoding = "2.1.2"
scoped_threadpool = "0.1.9"
clap = "2.33.0"
arrayref = "0.3.5"
serde = "1.0.99"
serde_yaml = "0.8"
